name: Continuos Integration and Deployment

on:
  push:
    branches:
      - master

jobs:
  CI:
    name: Continuos Integration
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
        run: 'npm install'
      - name: Check ESLint
        run: npm run lint
      - name: Make the environment file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NODE_ENV: ${{secrets.NODE_ENV}}
          envkey_PORT: ${{secrets.PORT}}
          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
          envkey_DATABASE_HOST_PROD: ${{secrets.DATABASE_HOST_PROD}}
          envkey_DATABASE_PORT_PROD: ${{secrets.DATABASE_PORT_PROD}}
          envkey_DATABASE_NAME_PROD: ${{secrets.DATABASE_NAME_PROD}}
          envkey_DATABASE_USER_PROD: ${{secrets.DATABASE_USER_PROD}}
          envkey_DATABASE_PASSWORD_PROD: ${{secrets.DATABASE_PASSWORD_PROD}}
          fail_on_empty: true
      - name: Run migrations
        run: npm run migration:run
      - name: Run unit tests
        run: npm run test
      - name: Run E2E tests
        run: npm run test:e2e

  CD:
    name: Continuos Deployment
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Load cached NPM dependencies
        id: cached-npm-dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('**/package.json') }}
      - name: Install dependencies
        if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
        run: 'npm install'
      - name: Deploy using sls
        run: 'npx sls deploy'
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
